### ISSUE TITLE
Open files in hidden buffers

### ISSUE THREAD

**Issue by aborilov** [szw/vim-ctrlspace#101]
I don't know how this happen, but very often after sometime, new files that I open through C-Space C-O opens in hidden buffer. I can see opened files only if press 'a' in file list. If I save workspace and restart Vim, then load this workspace, those files still will be in hidden buffer, but if I hit Enter, to open it, file will appear in current tab files list.
Why this happen, what I'm doing wrong?

**Comment by szw** [comment]
Hey!

Hmm, seems strange. Actually I never experienced anything like that. Could you try to provide extact reproduction steps and your Vim/system details. Also, if some pattern occured, please try it against a vanilla Vim instance (without any other plugins) and of course please make sure you have the newest version of Vim-CtrlSpace.

Cheers!

s.

**Comment by aborilov** [comment]
Hi!
I use vim 7.4 on ubuntu 12.04.5.
In this asciinema you can see my problem https://asciinema.org/a/15529
In words:
I open BufferList, press 's' to split, then close this split with ':q', and that is all. After that I try to open file from FileList with 'shift-o' and its opened in hidden buffer.
I think my problem is that I closed split with ':q'.
How to do it right?

**Comment by aborilov** [comment]
OK, I found something important, this happen only with python files with pymode enabled.

**Comment by szw** [comment]
So I guess it's related to pymode...
