### ISSUE TITLE
Using fzf for fuzzy finding

### ISSUE THREAD

**Issue by lazywei** [szw/vim-ctrlspace#102]
Hi,

It seems to me the fuzzy search is a little slow in large project. In fact, there is a super fast fuzzy finding (filtering) engine: [fzf](https://github.com/junegunn/fzf). I'm wondering if you can migrate the fuzzy finding to using fzf, or if you could provide an example how I can configure ctrlspace to use fzf?
Thanks.

**Comment by szw** [comment]
Hi,

Nope, currently it isn't possible. Fzf seems nice but it searches through files, and the fuzzy search in CtrlSpace is more general. Have you tried the Vim-CtrlSpace with a decent Ruby bindings? It speeds up the fuzzy search remarkably. Perhaps, in the future, another implementation of Vim-CtrlSpace's fuzzy algorithm could be made with Go.

**Comment by lazywei** [comment]
Hi,

1. FZF is just a filtering engine. You can pass any thing to it, e.g. through STDIN, and it will help you search anything you want. So I think any search in CtrlSpace is possible to use FZF as backend engine.
  For example,
  ```
  find * -type f | fzf > selected
  ```
  Or moreover, it can be used to replace search-in-buffer in vim: https://github.com/junegunn/fzf#usage-as-vim-plugin
  So I think it's possible to back CtrlSpace by FZF.

2. Yes, I have Ruby binding in Vim. However, it's a little bit slow in a project contains maybe thousands for ten thousands of files.

Thanks.

**Comment by szw** [comment]
1. Well, when I have more time I'll look at this more carefully. Of course pull requests are always welcome, and we could even have a special branch for that kind of integration.

2. You can also poke with some configuration variables like: [`g:ctrlspace_max_search_results`](https://github.com/szw/vim-ctrlspace#gctrlspace_max_search_results) or [`g:ctrlspace_search_timing`](https://github.com/szw/vim-ctrlspace#gctrlspace_search_timing).

**Comment by lazywei** [comment]
Sure, thanks for your replying. Could you give me some hints or instructions how I can dig the search functions in CtrlSpace deeper so I can try to play with the search+fzf?
Thanks.

**Comment by lazywei** [comment]
This got worse... when there are more than 30k files in projects. `o` freezes my vim.
I think there could be some improvements
1. search w.r.t. ignoring files (files in .gitignore)
2. make a explicit searching API, so that I can replace the search back-end with fzf.

For 2., I think the searching is done in ruby script, right? Does that mean I can call fzf in ruby script (in case vim +ruby enabled)?

Thanks.

**Comment by szw** [comment]
I've started a big chunk of refactoring in order to make the search engine pluggable. And yes, I will provide a Go one, however that would be a custom implementation independent from fzf (with all respect ;). All that stuff will go to branch `version_5`. I will update you once it is completed in an usable form :)

**Comment by lazywei** [comment]
Awesome! Thanks for letting me know. Really look forward to it :D



-- Chih-Wei
