### ISSUE TITLE
Unknown function: systemlist

### ISSUE THREAD

**Issue by denzeljiang** [szw/vim-ctrlspace#103]
Hi, this is an awesome plugin, but just got a gotcha when I was poking my `.vimrc` on ubuntu 14.04.
Seems like `ctrlspace` calls `systemlist` that is absent in vim.

![screenshot 2015-01-23 at 8 52 05 pm](https://cloud.githubusercontent.com/assets/469551/5885690/ecbbb8e2-a341-11e4-9709-fcfb12d0f8e6.png)

The version of vim is `7.4.52`. It comes from APT(official mirror).
It would be great if it's more backward compatible with vim.

**Comment by szw** [comment]
:+1: Yeap, you're absolutely right. Thanks for that :).
