### ISSUE TITLE
Error on :CtrlSpaceSaveWorkspace(cr) if no workspace exists

### ISSUE THREAD

**Issue by Konfekt** [szw/vim-ctrlspace#107]
If not, one erroneously assumes that the workspace has been saved, but only later realizes that no default name had been given. 

Perhaps better still, asks for a name if there is none yet instead of throwing an error.

**Comment by szw** [comment]
What are the extact steps to reproduce?

**Comment by Konfekt** [comment]
Just hitting :CtrlSpaceSaveWorkspace(cr) in a git project where no workspace has yet been saved.

This does not occur for (c-s)  after :CtrlSpace(cr) by the way.

**Comment by Konfekt** [comment]
Ah, perhaps the title is misleading: I'd like there to be an error message on `:CtrlSpaceSaveWorkspace<cr>` if no workspace exists.

Because if there is none, then the user erroneously assumes that the workspace has been saved, but only lateron she realizes that no default name had been given.

**Comment by szw** [comment]
Ah! Now I hear you :) Alright, I'll think about it!

**Comment by Konfekt** [comment]
:+1: In fact, better still if it asks for a name if there is none yet instead of throwing an error. So in the end, I'd only like it to act like `<c-s>` after `:CtrlSpace<CR>`.

**Comment by szw** [comment]
:+1: True. That would be the most reasonable behavior.

**Comment by szw** [comment]
For now I decided to go with plain error msg. But I did a lot of improvements regarding active workspace across various projects
