### ISSUE TITLE
Command to finish task directly from search?

### ISSUE THREAD

**Issue by jasonkuhrt** [szw/vim-ctrlspace#108]
In `search` mode it seems that `<CR>` merely brings us back to the parent mode upon which another `<CR>` will have the effect that was desired at search time as it were.

![screen shot 2015-03-08 at 9 37 31 pm](https://cloud.githubusercontent.com/assets/284476/6548804/9c3bae1a-c5db-11e4-828c-5389d6a2593e.png)

It would be nice to to support a new command like shift-enter that can just complete our action right then and there.

**Comment by szw** [comment]
In the version 5 the TAB key in the Search Mode provides that behavior.

**Comment by jasonkuhrt** [comment]
Cool, thanks for the update. I myself have moved on to `spacemacs` for a while now. Anyways, cheers.
