### ISSUE TITLE
Loading vimscript(s) for workspace

### ISSUE THREAD

**Issue by dodomorandi** [szw/vim-ctrlspace#109]
Is it possible to add a config option to load a vimscript file inside project trees?
i.e.: something like
let g:ctrlspace_autoload = '.autoload.vim'

In this way it could be possible to set specific options for different project.
Maybe the best could be allowing a special token for the workspace, like [[workspace]]. In this way you could also do something like
let g:ctrlspace_autoload = '.autoload_[[workspace]].vim'

Within the same project tree, different workspaces could use different loading scripts.
Just a couple of ideas to make ctrlspace even better. :=)

P.s.: ctrlspace changed my vim-life! Thank you guys!

**Comment by szw** [comment]
Ok, with new **Version 5** it's possible! :) Here's the solution:

1) Put this to your `.vimrc`
```VimL
function! LoadWorkspaceSettings()
    let fname = fnamemodify(".autoload_" . ctrlspace#modes#Modes().Workspace.Data.Active.Name . ".vim", ":p")
    if filereadable(fname)
        silent exe "source " . fnameescape(fname)
    endif
endfunction

au SessionLoadPost * call LoadWorkspaceSettings()
```

2) Place some settings in the your desired `.autoload_[workspace_name].vim` file. 

To verify I just did:

```VimL
let g:MyCustomSetting = "Custom autoload file"
```

Hopefully you will find this solution useful. 

Cheers!

s.

**Comment by dodomorandi** [comment]
Maybe it is not the most intuitive way, but... You are great! One of the best vim plugin ever!

You rock @szw!!

**Comment by szw** [comment]
:blush: Thanks for kind words :) I'm glad you enjoy it! :v:
