### ISSUE TITLE
Save/Restore terminal buffers in neovim

### ISSUE THREAD

**Issue by hoschi** [szw/vim-ctrlspace#110]
When opening a terminal with `:terminal` these buffers aren't saved in the workspace. Would be great when these buffers would also be saved/restored.

**Comment by szw** [comment]
Yes, currently workspace saving uses Vim session mechanics. It is possible to provide a limited support for various non-standard Vim buffers, and perhaps I would allow/apply more buffer types (NERDTree windows, etc.). Right now however I'm focusing on a next [plugin version](https://github.com/szw/vim-ctrlspace/tree/version_5) that will bring lots of refactorings and eventually make all those improvements easier.

**Comment by szw** [comment]
I can only guess what that `:terminal` do, but sometimes I do use a [terminal in Vim](https://github.com/oplatek/Conque-Shell). Still I don't think those buffers (term sessions) should be saved somehow (recreated). Moreover, IMO in some circumstances that could be even dangerous or not effective (ssh sessions?) and annoying.

**Comment by hoschi** [comment]
`:terminal` is a native version of Conque-Shell, see http://neovim.io/doc/user/nvim_terminal_emulator.html

I try to replace tmux with nvim+terminal-mode, so this was the reason why I got into this problem of saving/restoring terminal buffers. As nvim+terminal-mode has some down sides in favor of tmux it could also has some advantages as terminals 'per session' when the session manager handles this type of buffer. Here are some examples:
* working with content which lists files, a terminal buffer beside this which has the correct `cwd` set allows you modifications of files and the list of files pretty easy
* package.json + terminal to install packages with `npm`
* Gulpfile + terminal to run gulp tasks
* Gstatus buffer (e.g. fugitive plugin) + terminal for more advanced git commands + terminal which shows auto updating git log
* Dashboard tab with long running tasks e.g. dev server to host app on local domain, tailing some logs, overall status of JSHint errors of all sources

Some types of examples above should be in every session, this works already when starting with a 'main' session and copy this session to a new session. Other types of examples are only used in specific tasks, e.g. the file editing example or gulp editing example.

I would love to hear your thoughts about this :)

**Comment by hoschi** [comment]
> Moreover, IMO in some circumstances that could be even dangerous or not effective (ssh sessions?) and annoying.

This could be handled by white/blacklisting executables when restoring, like this one https://github.com/tmux-plugins/tmux-resurrect#configuration

**Comment by szw** [comment]
This sounds a bit scary ;). Personally I'm not sure, whether replacing tmux with (Neo)Vim is right, but perhaps if it works and it's robust... Hard to avoid similarities to Emacs though. BTW. In Conque term I used to go start tmux anyway. 

Currently I'm not going to implement any temporary buffers into session save/restore. But if I have a pull request I would consider merge.

**Comment by szw** [comment]
If that NeoVim terminal is a native one, the perhaps they would build it in into the `session` feature. In that way you would have it supported almost ottb.
