### ISSUE TITLE
Easier process to save workspace

### ISSUE THREAD

**Issue by brandonw** [szw/vim-ctrlspace#111]
I would like the ability from within the workspace list to be able to save the current workspace.

Right now, if I have an existing workspace, and I make a new one, the only way I have found to save it is to manually call :CtrlSpaceSaveWorkspace [name]

It would be nice to have the current workspace show up as [unnamed] or something along those lines, and be able to use the = key to rename it.

**Comment by szw** [comment]
Actually you can save the workspace by changing the workspace mode to "save" with the `s` key. Renaming should also work :)

**Comment by brandonw** [comment]
Thanks. I remember trying to use workspace save mode before, but that was when I had a reasonably complex workspace set up and I wasn't sure exactly how to use it so I didn't want to mess it up.

Now that I go back into it again, it does seem straightforward enough to go into workspace save mode and hit enter. I think my confusion before was because you are prompted to save the current workspace as a certain name, but you can still select a workspace in the list (even though the current selection has no bearing on the save operation, that I can discern). I think my fear before was that it was prompting me to save the workspace over the currently selected workspace

Either way, looks like it is handled after all. Thanks!

**Comment by brandonw** [comment]
I guess the current selection does have a purpose as well: the default name of the workspace you are saving. Thanks again for the tip :)
