### ISSUE TITLE
Opened wrong files in workspace relative to project "root"

### ISSUE THREAD

**Issue by DelvarWorld** [szw/vim-ctrlspace#112]
I have a folder structure:

    root/
        .git/
        project1/
        project2/

When I work in `project1`, my `:pwd` is `project1`. I'm also using [vim-project](https://github.com/amiorin/vim-project) which sets the pwd to `project1/` if you're editing a file in a subfolder of `project1` (very nice).

I saved a workspace in one vim session, with lots of files open like `root/project1/folder/file.txt`, with Vim showing me the relative path as `folder/file.txt`which is correct.

Then I opened Vim, switched to my project with vim-project (which basically sets `:pwd` to `project1/`, then I loaded the workspace. Now all of my paths are wrong because it mangled the relative paths. It tried to load relative path `project1/folder/file.txt` when it should be loading `folder/file.txt` which is correct relative to the `:pwd`.

I'm not sure if the workspace is saved relative to a git directory which is why I included the git folder in the example structure. I have multiple "projects" as a subdirectory of one git repo, and ctrlspace doesn't seem to handle that.

**Comment by szw** [comment]
You should add custom project roots for your projects (check `:help :CtrlSpaceAddProjectRoot`).

**Comment by DelvarWorld** [comment]
Calling `Project  '~/path', 'identifier'` doesn't do this automatically?

**Comment by szw** [comment]
Are you referring to vim-project? I don't know that plugin..

**Comment by DelvarWorld** [comment]
Oh whoops, sorry, got my repos mixed up

**Comment by szw** [comment]
no problem :)
