### ISSUE TITLE
default mapping doesn't work on vim 7.4, patches 1-694

### ISSUE THREAD

**Issue by montefra** [szw/vim-ctrlspace#114]
Opensuse Tumbleweed yesterday updated vim from 7.4.683 to 7.4.694. But now the default mapping <C-Space> doesn't work anymore.

I've tried to explicitly set 

    let g:ctrlspace_default_mapping_key = "<C-Space>"

to no avail, although setting it to an other mapping, e.g. ``<F2>``, it works. 

On the other hand on my kubuntu machine, with vim 7.4.273, the plugin works.

If you need any further info, let me know.

----

[My vim settings](https://github.com/montefra/.vim).

Tumbleweed update notification:
```
==== gvim ====
Version update (7.4.683 -> 7.4.694)
Subpackages: vim vim-data

- Updated to revision 694, fixes the following problems
  * When starting several Vim instances in diff mode, the temp files
    used may not be unique. (Issue 353)
  * When there are illegal utf-8 characters the old regexp engine may
    go past the end of a string.
  * "zr" and "zm" do not take a count.
  * There is no way to use a different in Replace mode for a terminal.
  * When "$" is in 'cpo' the popup menu isn't undrawn correctly.
    (Issue 166)
  * Memory access errors when changing indent in Ex mode. Also missing
    redraw when using CTRL-U. (Knil Ino)
  * Can't build with MzScheme.
  * Session file is not correct when there are multiple tab pages.
  * Running tests changes the .viminfo file.
```

**Comment by montefra** [comment]
"Magically" this problem disappeared. I just realised that I can use again ctrl-space key binding. I don't know since when, though.

**Comment by szw** [comment]
:cool: :) You can try also the upcoming version_5 (assuming you use Vundle):

```
cd ~/.vim/bundle/vim-ctrlspace
git fetch
git checkout version_5
```

**Comment by montefra** [comment]
I might give a try.

BTW: I use junegunn/vim-plug, but it should be similar to try it
