### ISSUE TITLE
taboo.vim

### ISSUE THREAD

**Issue by korin** [szw/vim-ctrlspace#121]
Is there any chance that this plugin can work with [taboo.vim](https://github.com/gcmt/taboo.vim)?
Right now command TabooRename (from taboo.vim) not work when I have both plugins installed.

**Comment by korin** [comment]
I ask the same question here gcmt/taboo.vim#8

**Comment by korin** [comment]
I just found https://github.com/tpope/vim-flagship but I think both plugins should use it to make it work. Right?

**Comment by szw** [comment]
Well, I guess both plugins use their own tools and follow their own ways to achieve similar goals. Vim-CtrlSpace has its own tab naming and managing system. Other plugins might make use of it. In the new version (5.0) it would be even easier. 

BTW. The new upcoming version is in an early beta!

**Comment by korin** [comment]
Nice. I didn't know that I can rename tab with CtrlSpace. I reread README carefully and found [tab-management](https://github.com/szw/vim-ctrlspace#tab-management) and [tabs-operations](https://github.com/szw/vim-ctrlspace#tabs-operations).

Thank you for help. BTW great plugin.
I'm closing this issue because that resolves my problem.

**Comment by szw** [comment]
:+1:
