### ISSUE TITLE
File content deleted after move or rename

### ISSUE THREAD

**Issue by commaster90** [szw/vim-ctrlspace#122]
After renaming a file in the buffer list, the file content gets deleted. This happens if the renamed file is not the current active buffer.

**Comment by szw** [comment]
Hmm, I saw similar issue somewhere here, but AFAIR I couldn't reproduce it. Similarly I cannot reproduce it now. Please share more details about your setup. 

BTW. Just in case please check if the problem occurs within a new plugin [version (5)](https://github.com/szw/vim-ctrlspace/tree/version_5). It's upcoming release (hopefully at this weekend!) and all fixes will go there anyway.

**Comment by commaster90** [comment]
I tested it with a minimal setup on a Ubuntu Server 14.04 VM. The only plugins installed were Vundle and vim-ctrlspace.

Here is what I did.

1. Start vim. 
2. Edit a file. ":e a.txt"
3. Insert some text. Then save the file with ":w".
4. Edit or open another file with ":e b.txt".
5. Now activate ctrlspace and the buffer will show "a.txt" and "b.txt" files. Point the selection at "a.txt" and press "m" to rename the file to "c.txt".
6. Now switch to edit the file "c.txt". The contents are deleted!

The same happens for version(5) branch.

**Comment by ryrych** [comment]
I tried the workflow in [Version 5](https://github.com/szw/vim-ctrlspace/tree/version_5) on MacOS X and can't confirm the issue.

Could you please paste the content of `:messages` when this happens again?

**Comment by szw** [comment]
Hmm, I've installed Ubuntu 14.04 and vim-nox on VirtualBox. Then I created a simple .vimrc with Vundle and Vim-CtrlSpace. The .vimrc you'll find [here](https://gist.github.com/szw/04686f54d79463abd562).

And here's the [Asciinema session](https://asciinema.org/a/2756xx8y5a8tep6a0izeovuj8). Still no luck with reproducing. :/

**Comment by commaster90** [comment]
@szw It turns out the bug doesn't happen when I use your .vimrc file.

So I did a quick check by turning the options on and off, and I found that the cause is a missing "set hidden" option. I have no idea about the "set hidden" option though.

**Comment by szw** [comment]
Good catch! It's indeed recommended: https://github.com/szw/vim-ctrlspace#getting-started. Perhaps it's high time to make it a prerequisite for the plugin...

BTW. _hidden_ allows you to have unsaved buffers in the background (not visible anywhere). It's pretty natural for this kind of plugin. But still the correlation between renaming and hidden option is not obvious for me :]. Anyway, I'll try to handle it somehow in the upcoming v. 5 :)

**Comment by szw** [comment]
I've added requirements for 'nocompatible', 'hidden' and Vim version 7.3 at least to the version_5 branch.

**Comment by commaster90** [comment]
:+1:
