### ISSUE TITLE
Go default in Tablist instead of bufferlist

### ISSUE THREAD

**Issue by mbrinkme** [szw/vim-ctrlspace#123]
It's possible to set up the default behavior from CTRL Space from going directly to tablist instead of bufferlist?

**Comment by szw** [comment]
Not directly at this moment. However there is a workaround. You can use the command `:CtrlSpace l` to open CtrlSpace in Tab List view. You can also map this command to your desired key.

**Comment by mbrinkme** [comment]
That works perfect for me! 

Here are my mappings to go directly with e.g. <leader>1 to the first Tab.
```
nmap <leader>l :CtrlSpace l<CR>
nmap <leader>l :CtrlSpace l<cr>                                                                                   
nmap <leader>1 :CtrlSpace l<cr>1<cr> 
nmap <leader>2 :CtrlSpace l<cr>2<cr>
...
```

**Comment by szw** [comment]
In the new CtrlSpace v.5 keys from 1 up to 0 are not mapped. It's because CtrlSpace encourages you to use even more tabs. However it's possible to add your custom mappings and functions, so that behavior can be easily restored. But in your particular case perhaps there is no need to involve Vim-CtrlSpace to change tab. Check out these mappings:
```
nmap <leader>1 1gt
nmap <leader>2 2gt
...
```

**Comment by mbrinkme** [comment]
I test these mappings, but they didn't work. 

My mappings still work. 
```
nmap <leader>1 :CtrlSpace l<cr>1<cr> 
nmap <leader>2 :CtrlSpace l<cr>2<cr>
...
```

**Comment by szw** [comment]
Alright, I think I misunderstood what those mappings were supposed to do. You want to open a list for given tab with `<leader>` and number, right?

Here's a solution that hopefully would work in both versions (4 and 5). 
```VimL
nmap <silent><leader>l :CtrlSpace l<CR>
nmap <silent><leader>1 1gt:CtrlSpace<cr>
nmap <silent><leader>2 2gt:CtrlSpace<cr>
```
