### ISSUE TITLE
Allow more navigation in help view

### ISSUE THREAD

**Issue by rgrinberg** [szw/vim-ctrlspace#126]
I find myself reaching for:

* `/` to search

* `gg` go to start of help buffer

* `G` go to end of help buffer

**Comment by szw** [comment]
* For `gg` you can use `<K>`
* For 'G' go with '<J>'
* For `/` there is an issue #98 still open ;)

However I'm not sure how to provide searching in Help Mode, as the help works also with Search Mode itself. How to allow to search while searching and not confuse users? ;)

PS. All normal navigation works in Help Mode, like `<C-d>` and `<C-u>`, etc.

**Comment by rgrinberg** [comment]
Ah ok then I'll close this one. It would be nice to remap `K` and `J` though to g/GG.
