### ISSUE TITLE
background color is now purple

### ISSUE THREAD

**Issue by montefra** [szw/vim-ctrlspace#127]
I've updated the plugin to v5.0 just today and used it very briefly on two different machines with Kubuntu 15.04.
Before the update the ctrlspace slit was with a black background, with a light gray background for the cursor line:
![ctrlspace_before_update_bufflist](https://cloud.githubusercontent.com/assets/1394820/9123925/2593ddf8-3c93-11e5-8435-ba5ec8f800e5.png)
![ctrlspace_before_update](https://cloud.githubusercontent.com/assets/1394820/9123808/2aa07f00-3c92-11e5-9840-a28c97db450e.png)

Now the background color is purple, with the cursor line in black:
![ctrlspace_after_update_bufflist](https://cloud.githubusercontent.com/assets/1394820/9123863/9daa463e-3c92-11e5-8011-a59d4a095ca1.png)
![ctrlspace_after_update](https://cloud.githubusercontent.com/assets/1394820/9123809/2aa16956-3c92-11e5-8d36-ed6bdc42e9c7.png)

I cannot say that I like the color. 

In the documentation there are four highlight schemes:

    hi link CtrlSpaceNormal   PMenu                                                                                                     
    hi link CtrlSpaceSelected PMenuSel                                                                                                  
    hi link CtrlSpaceSearch   Search                                                                                                    
    hi link CtrlSpaceStatus   StatusLine

Is any of them dealing with the background? If know, which ``highlight`` is responsible for it?

my vimrc and customizations are [here](https://github.com/montefra/.vim)

Mildly related: do you know if it's possible to disable spell check in the ctrlspace split only, so that the annoying red blocks disappear?

**Comment by szw** [comment]
:smile_cat: looks crazy :) :eyes: 

Try put this: 

```viml
hi link CtrlSpaceNormal Normal                                                                                                     
hi link CtrlSpaceSelected Visual
```

To explore more options try:

```viml
:hi
```

Regarding spell checking, thanks for reporting this. Spell checking should be turned off in the plugin window. I will provide a fix a few minutes :)

**Comment by montefra** [comment]
I'll give a try tomorrow. This is what ``:hi`` shows

    Pmenu          xxx ctermfg=0 ctermbg=13 guibg=Magenta
    PmenuSel       xxx ctermfg=242 ctermbg=0 guibg=DarkGrey
    PmenuSbar      xxx ctermbg=248 guibg=Grey
    PmenuThumb     xxx ctermbg=15 guibg=White

I use vim in Konsole, not in gvim, and correctly ``has("gui_running")`` returns ``0``. Nonetheless it uses the ``guibg`` color, apparently.

Thanks for fixing the spell check.

**Comment by szw** [comment]
Well, I advised you the `:hi` command to let you see how various highlight groups look in your Vim. Just pick names looking best for you and put them into into those `hi link CtrlSpace...` command series. The `Normal` and `Visual` groups were used by default in the Version 4.

BTW. There are plenty of color schemes for Vim, far better than those pink defaults ;). It seems you don't use any colorscheme currently so perhaps it's worth to try [find something](http://vimcolors.com) :cool:.

**Comment by montefra** [comment]
I know that there are a lot of color schemes. I went through a number of them some times ago, but got back to default one. Thanks for the link and for disabling the spell checking.
