### ISSUE TITLE
ctrlspace has problems loading a workspace when working along GoldenView.vim

### ISSUE THREAD

**Issue by yacoob** [szw/vim-ctrlspace#128]
I use [zhaocai/GoldenView.Vim](https://github.com/zhaocai/GoldenView.Vim) for automatic window resizing. However, when it's loaded, ctrlspace seems to have problems loading a workspace back. It fails at some stage between first and second buffer, never succeeding past that first one. Here are the errors I can see in `:messsages`:

```
Error detected while processing /Users/yacoob/workarea/CS_SESSION:
line   26:
E591: 'winheight' cannot be smaller than 'winminheight': winheight=1          
```

I guess it'd make sense to disable GoldenView for the time of workspace restoration - and it seems to have some facilities for this purpose. However my vimscript-fu is way too weak to provide some working solution together with this bug report. :)

**Comment by szw** [comment]
Hmm... This CS_SESSION stuff is just a session written by Vim `:mksession` feature. CtrlSpace inject just a few insertions into that code, and none of them are related to windows layout. I think GoldenView would break also a standard session sourcing (restoration). 

By default Vim put `let SessionLoad = 1` at the beginning of session loading and remove (unlet) this global variable once the session loading is done. In that way plugins might detect whether the session loading is in progress and do not interfere with that. 

IMHO GoldenView should check within its auto commands whether the `SessionLoad` variable exists and prevents any actions if it's set to 1.

**Comment by yacoob** [comment]
Right, I've tested things, and sure enough, same kind of problems happen during sourcing a file made via `:mksession`. Judging by the activity on the GoldenView repo, it's abandoned and this kind of bug won't be fixed. If you think you can somehow address this in ctrlspace, please keep this bug open - otherwise please close it.

Thanks for help in debugging :)

**Comment by szw** [comment]
I've just briefly looked at that plugin... 
How about sth like: 

```VimL
if exists("g:SessionLoad") && g:SessionLoad
    return
endif
```

inserted into [this line](https://github.com/zhaocai/GoldenView.Vim/blob/master/autoload/GoldenView.vim#L168). If it works then you could have a fork and use it instead. :]
