### ISSUE TITLE
Please autodetect and configure g:CtrlSpaceFileEngine

### ISSUE THREAD

**Issue by yacoob** [szw/vim-ctrlspace#129]
Is there any reason not to? There should be enough clues in vim's environment to tell what OS it's running under, and as a result which binary to use.

**Comment by szw** [comment]
Of course I thought about it. But it's tricky and would require some experimenting. For me, it's relatively easy to detect whether it's Linux or Darwin (OS X) (`uname -sm`). It's also easy to detect if it's Windows (`has("win32")`)... But then how to get whether it's 32 or 64? How to detect ARM (Raspberry PI?). 

As I didn't know exact answer I decided to not go without a robust solution for the release. But I'm open to pull requests or at least some help from users (perhaps owners of such devices?). Once we have this detection steps recognized we could provide an automatic detection feature.

**Comment by yacoob** [comment]
Well, you can autodetect in the cases that you know, and leave things unset in the unknown cases. I also think that output of `uname -a` should contain everything that's needed for the decision.

**Comment by szw** [comment]
Well, for Unix that's the way... On the other hand I don't like a partial detection as IMO it would confuse people. Perhaps if we have a solution for windows and ARMs then we could provide auto detection at least for most popular platforms.. 

BTW. It's still relatively easy to provide simple autodetection in `.vimrc` if necessary (if one for example shares `.vimrc` among various Unix machines).

**Comment by szw** [comment]
Well, some initial implementation is done. Hopefully it will work for most cases.
