### ISSUE TITLE
CtrlSpaceIgnoredFiles, Wildignore, Ag .gitignore not working

### ISSUE THREAD

**Issue by godenji** [szw/vim-ctrlspace#130]
Just upgraded to 5.0, liking everything so far (great plugin) with the exception of search lists -- no matter what I do ctrlspace pulls in contents of every directory in current project.

From [this issue](https://github.com/szw/vim-ctrlspace/issues/49) I have tried:
~~`let g:ctrlspace_glob_command = 'ag -l --nocolor -g ""'`~~
`let g:CtrlSpaceGlobCommand = 'ag -l --nocolor -g ""`

and from [this one](https://github.com/szw/vim-ctrlspace/issues/120) I have tried setting `wildignore`

I have also tried setting `CtrlSpaceIgnoredFiles` and commenting out `CtrlSpaceFileEngine` and `CtrlSpaceGlobCommand`.

Nothing works. What is the secret sauce to get search lists reduced from several thousand files to just the contents of working directories?

**Comment by szw** [comment]
Hmm... please be more specific. CtrlSpace is supposed to get content of every directory in the project. Why do you expect it to omit some?

BTW. To use `ag` you should definitely go with `leg g:CtrlSpaceGlobCommand`variable (the _snake case_ one is for Version 4.x).

**Comment by godenji** [comment]
> Hmm... please be more specific. CtrlSpace is supposed to get content of every directory in the project. Why do you expect it to omit some?

Because when you have, for example, more than 10K generated `.class` files in compile target directory (JVM project), and the contents of those files are binary, there is absolutely no reason to have the directory contents be searchable ;-)

> BTW. To use ag you should definitely go with leg g:CtrlSpaceGlobCommandvariable (the snake case one is for Version 4.x). 

I am, just copy-pasted from the first linked issue.

I would think that `.gitignore` contents, via wildignore or ag would omit applicable files and directories from search path. Is this functionality not possible with ctrlspace?

**Comment by szw** [comment]
I've just briefly verified `Ag` and it follows `.gitignore` as expected. You can check it yourself on this plugin repo. Clone plugin repo, set Vim's CWD to this project, add to `.gitignore` for example:
```
bin/**
```

You won't see any `bin/`files once refreshed (`<r>` in the File List).

**Comment by szw** [comment]
Still cannot verify this issue. I'm trying to reproduce:

```
mkdir classes
cd classes
touch foo.class
touch bar.class
```

Files are visible. Then I put to `.vimrc`:

```
let g:CtrlSpaceIgnoredFiles = '\v\.class$'
```

After restart of Vim and refreshing files list of that project `*.class` dissapear...

**Comment by szw** [comment]
Please also check Vim Regex format:

    :help \v

**Comment by godenji** [comment]
Strange, not sure what happened to my reply yesterday (less than a minute after your, "I've just briefly verified Ag and it follows .gitignore as expected.") stating that the issue is solved.

Anyway, `<r>` refresh was the missing piece, file cache must not have cleared when upgrading to 5.0.

All set now, thanks!

**Comment by szw** [comment]
:+1:
