### ISSUE TITLE
Configurable key mappings

### ISSUE THREAD

**Issue by phairland** [szw/vim-ctrlspace#131]
Hi, 

There is no information on the readme as to how to configure your own key mappings. Please I need this before upgrading to Version 5. Thank you

**Comment by szw** [comment]
That's true. I'd like to keep README concise. If you want to read it before upgrading (after upgrade it's available through `:help g:CtrlSpaceKeys`) then [check here](https://github.com/szw/vim-ctrlspace/blob/master/doc/ctrlspace.txt#L870-L923).

**Comment by phairland** [comment]
Thank you, my apologies for being in a hurry ;-) CtrlSpace is such a great tool !!!

**Comment by szw** [comment]
No need for apology ;). Enjoy :)
