### ISSUE TITLE
breaks vim plug lazy load

### ISSUE THREAD

**Issue by agauniyal** [szw/vim-ctrlspace#133]
I have defined YCM plugin in my `.vimrc` as follows 

```
Plug 'Valloric/YouCompleteMe', { 'do': './install.sh --clang-completer --system-libclang', 'for': ['cpp', 'hpp', 'h'] }
```

and while this works in every scenario, I have found it to be broken when I load a c++ source file via ctrlspace workspaces. After I saw completions were not coming up, I tried invoking YCM manually via :Ycm* commands, only to find there were no such commands defined and pressing <tab> wasn't showing any completions for it.

Since I do not know which plugin is causing issue here, I'm filing a cross-issue with vim-plug too so that it gets resolved as early as possible.

https://github.com/junegunn/vim-plug/issues/265

**Comment by szw** [comment]
Vim-CtrlSpace uses plain Vim session feature. Please save and load a Vim session (`help :mksession`) to see whether YCM works for your cpp files or not.

**Comment by agauniyal** [comment]
@szw apparently it was an issue with YCM not getting loaded. 

>The reason YCM does not load is that it only executes its Enable function on VimEnter, so it has to be manually triggered.

I added following line into my `~/.vimrc` and YCM works again.

`autocmd! User YouCompleteMe call youcompleteme#Enable()`

**Comment by szw** [comment]
Alright! :+1:
