### ISSUE TITLE
Map <C-p> to File Fuzzy Open

### ISSUE THREAD

**Issue by sittim** [szw/vim-ctrlspace#134]
Awesome Plug in, thank you, I am just changing from Sublime Text to VIM, would it be possible to map `<C-p>` to fuzzy open, so it would be:
`<C-Space>O`
This is probably a silly question, but I am so new to VIM that I do not know how to do it...

**Comment by szw** [comment]
Thanks! I'm glad you like it :smiley_cat:  Try out this mapping (paste it to your `.vimrc`):

```VimL
nnoremap <silent><C-p> :CtrlSpace O<CR>
```

**Comment by sittim** [comment]
Your plug in is perfect, it solves a ton of problems, things I love about it

- workspace save/open
- quick buffer navigation
- <C-p>, it is much better then the CtrlP plug-in because it allows you to add a workspace directory.

These are the things I use for C++ development, I plan to learn a lot more.

Thank you...

**Comment by szw** [comment]
:blush: Thank you :) For me, this is the challenge to provide easy to grasp scenarios showing plenty of use cases. I think of a series of asciinema screencasts (or just some animations) describing lot's of stuff (perhaps a project wiki?).

Meantime feel free to ask! There are no bad questions, and even simple ones can help others. For me it's also an important feedback to see whether sth is designed / explained well or not. 

And enjoy the Vim experience :).
