### ISSUE TITLE
Workspace Feature Request

### ISSUE THREAD

**Issue by sittim** [szw/vim-ctrlspace#135]
# Challenge

Every time I change workspace, I have to remap the <C-b> key, since each workspace requires a workspace specific makefile.

# Details

I develop in C++, when I develop a class, let say `RingBuffer`, I have the following files associated with it.

- `src/ring_buffer.h`
- `src/ring_buffer.cpp`
- `src/unittest/ring_buffer_test.cpp`
- `src/unittest/mock_ring_buffer.h`
- `src/unittest/ring_buffer.makefile`

When I work on the RingBuffer class, I have all these buffers open in windows and I keep the workspace saved.  To work on another class I just switch workspaces.  This saves a ton of time, *but every-time I switch the buffer, I have to update my <C-b> key binding to run shell command such as `make -f src/unittest/ring_buffer.makefile`*.  Is there a solution for such issue?

# Possible Solution (Sublime Text uses project specific configuration files)

Would it be possible, in the working directory to create files named `workspace_name.cs_workspace` and allow a user to add stuff like a key binding, for example:
`map <C-b> !make -f src/unittest/ring_buffer.makefile`

# How Sublime Text does it

Learning from Sublime Text, they use two files in this case it is for workspace called `resources`,  File Name: `resources.sublime-project`
```js
{
    "folders":
    [
        {
            "follow_symlinks": true,
            "path": "/work/fw/c1202-f5335",
            "folder_exclude_patterns": [
                "Debug",
                "targetConfigs"
            ],
            "file_exclude_patterns": [
                "*.ccxml",
                "*.plist",
                "*_test",
                "*.gch",
                "*.sublime-workspace",
                "*.o",
                "*.pp",
                "*.obj"
            ],
            "follow_symlinks": true
        }
    ],
    "settings":
    {
            "sublimegdb_workingdir": "/work/fw/c1202-f5335/dispatcher/unittest",
            // NOTE: You MUST provide --interpreter=mi for the plugin to work
            "sublimegdb_commandline": "gdb --interpreter=mi tstamp_test",
            "cc_include_options":
            [
                "-D _BIC_SR(X)=",
                "-D _BIS_SR(X)=",
                "-D STACK_LEN=32",
                "-D TASK_QTY=4",
                "-I/work/fw/c1202-f5335",
                "-I/work/gmock/include/",
                "-I/work/gmock/gtest/include",
                "-isystem", "/usr/include",
                "-isystem", "/usr/lib/llvm-3.6/lib/clang/3.6.2/include",
                "-Wall"
            ]
    },
    "build_systems":
    [
        {
            "name": "Resource",
            "shell_cmd": "make -f resource.makefile && ./resource_test",
            "file_regex": "^(..[^:]*):([0-9]+):?([0-9]+)?:? (.*)$",
            "working_dir": "${file_path}",
            "selector": "common_test.cpp"
        },
        {
            "name": "Resource Parent",
            "shell_cmd": "make -f resource_parent.makefile && ./resource_parent_test",
            "file_regex": "^(..[^:]*):([0-9]+):?([0-9]+)?:? (.*)$",
            "working_dir": "${file_path}",
            "selector": "common_test.cpp"
        }
    ]
}
```
The there is a file named `resources.sublime-workspace`

**Comment by szw** [comment]
Well, first of all I'm sure you don't need to switch workspaces to switch context to another file. Workspaces are like sessions. It makes more sense to create them per feature (or a feature branch) and combine within them all files and tabs related to the feature you're working on.

Regarding your case, you can create a general binding reusing your current file name, e.g. `exe "!make -f %"`. Check also some plugins designed specifically to boost C++ developing in a Vim way. :)

Nevertheless, it's also possible to have the exact behavior you requested. I mean to load custom preferences file per workspace. Have a look at the issue #109 and the answer.

**Comment by sittim** [comment]
OK, so the #109 looks promising.  I am switching workspaces to change context to a class, which can have 5 or more files associated with it.  Trust me on this, it awesome for C++ TDD (Test Driven Development) approach.  I will try to get the `LoadWorkspaceSettings()` to work, and then my work-flow will be nearly perfect.

**Comment by szw** [comment]
Well, if it works for you then sure, utilize this approach. Please just make sure if you really don't want to try use tabs instead of workspaces. I tend to have workspaces with even 100 files opened in 20-30 tabs. Some temporary, some named. Some holding project configuration. Other related to TDD and grouping classes and their test files... 

Anyway, just in case, as you came from Sublime, to better explain what I'm writing about, I created a simple demo ;) Here's an example of my approach: https://asciinema.org/a/3ub3kslryg77x02h6oiusc3z8. 
If you still sure you need workspaces and not tabs, then sure, go with whatever suits better your workflow.

**Comment by sittim** [comment]
OK, I understand, this may make it even simpler, so below is my VIM screen, it can be in one tab.

![selection_238](https://cloud.githubusercontent.com/assets/8825037/9250766/8251fa34-419d-11e5-85e7-d47d6d2c80a0.png)

Each file is opened in the order, from left to right.

- Class Header
- Class Source
- Class Mock
- Class Test

Looking at your previous comment regarding `!make -f %` if the name of my Class test source file is `class_name_unittest.cpp` is it possible to convert `%` from `class_name_unittest.cpp` to `class_name.makefile`, so effectively replacing `_unittest.cpp` with `.makefile`?

**Comment by szw** [comment]
Sure, there is a function in Vim Script named `substitute()` that would work for in this case:
```VimL
substitute("class_name_unittest.cpp", "_unittest.cpp", ".makefile", "")
```

**Comment by sittim** [comment]
Wow, That is very powerful, looks like I can do:

```c
!make -f substitute(%, "_unittest.cpp", ".makefile", "")
```

Problem solved, I will test it tomorrow, Thank you...

**Comment by szw** [comment]
:+1: It is ;)

The whole command could look like:

```VimL
exe "!make -f " . fnameescape(substitute(expand("%"), "_unittest.cpp$", ".makefile", ""))
```

`fnameescape()` escapes spaces. And `$` acts as in normal Regexes - binds pattern to end of the expression.

Anytime you can check detailed help, e.g.: 

```VimL
:help substitute()
```
