### ISSUE TITLE
Mismatch the file path after load the workspace

### ISSUE THREAD

**Issue by kangic** [szw/vim-ctrlspace#137]
First of all, thank you for enjoying the great plugin.
I work with the CtrlSpace to develop my project recently.

I have a little problem when load the workspace.
* I start vim in the project's root directory. And I open the below files.
  1. CMakeLists.txt<original tab>
  2. src/sys/io_manager.h<make a 'sys' tab>
  3. sys/io_manager.cc<'sys' tab> (CtrlSpace shows the different path - omit the 'src'.)
* Save the workspace after move to the project's root directory to open the CMakeLists.txt in the file list.
  - So then save the cs_workspace file in the .git directory.
* Quit the vim.
* Turn on the vim and load the workspace.
* But, its files are not match.
  - '[CMakeLists.txt]' tab. It has a file.
    - CMakeLists.txt (It's correct.)
  - 'sys' tab. It has 3 files.(I opened two files previously.)
    - src/sys/io_manager.cc(blank file)
    - src/sys/io_manager.h(blank file)
    - sys/io_manager.cc (It's correct.)

I modified the files' path in my cs_workspace file to fix the problem. Yes, it works fine to open the file.
But, I can't catch the problem correctly.

Additionally, I have two questions.
1. Should I move to the project's root directory before save the workspace?
2. Why it shows different path after open the file in the 'src' directory?

Please understand about that my English writing skill is not well.

Again, thank you for your effort to make a good plugin.

-----------------------------------------

Here's the additional data for understanding the problem.

My project directories.
* /home/raymondk/works/github/eznetpp(project's root directory)
  - .git
  - build
  - examples
  - src
    - sys
      - io_manager.h
      - io_manager.cc

My cs_workspace.
```
CS_LAST_WORKSPACE: eznetpp
CS_WORKSPACE_BEGIN: eznetpp
let SessionLoad = 1
if &cp | set nocp | endif
let s:so_save = &so | let s:siso_save = &siso | set so=0 siso=0
let v:this_session=expand("<sfile>:p")
silent only
exe "cd " . escape(expand("<sfile>:p:h"), ' ')
if expand('%') == '' && !&modified && line('$') <= 1 && getline(1) == ''
  let s:wipebuf = bufnr('%')
endif
set shortmess=aoO
badd +1 CMakeLists.txt
badd +1 src/sys/io_manager.h
badd +3 src/sys/io_manager.cc
argglobal
silent! argdel *
set stal=2
edit CMakeLists.txt
edit CMakeLists.txt
set splitbelow splitright
set nosplitbelow
set nosplitright
wincmd t
set winheight=1 winwidth=1
argglobal
let s:l = 1 - ((0 * winheight(0) + 26) / 53)
if s:l < 1 | let s:l = 1 | endif
exe s:l
normal! zt
1
normal! 0
tabedit src/sys/io_manager.cc
edit src/sys/io_manager.h
edit src/sys/io_manager.cc
let t:CtrlSpaceLabel = 'sys'
edit src/sys/io_manager.cc
set splitbelow splitright
set nosplitbelow
set nosplitright
wincmd t
set winheight=1 winwidth=1
argglobal
let s:l = 3 - ((2 * winheight(0) + 26) / 53)
if s:l < 1 | let s:l = 1 | endif
exe s:l
normal! zt
3
normal! 0
lcd ~/works/github/eznetpp/src/sys
tabnext 1
set stal=1
if exists('s:wipebuf')
  silent exe 'bwipe ' . s:wipebuf
endif
unlet! s:wipebuf
set winheight=1 winwidth=20 shortmess=filnxtToO
let s:sx = expand("<sfile>:p:r")."x.vim"
if file_readable(s:sx)
  exe "source " . fnameescape(s:sx)
endif
let &so = s:so_save | let &siso = s:siso_save
doautoall SessionLoadPost
unlet SessionLoad
" vim: set ft=vim :
CS_WORKSPACE_END: eznetpp
```

**Comment by szw** [comment]
Hmm, a couple of questions:

* Could you write more about your environment? 
* Could you verify the problem with a vanilla Vim and all other plugins turned off? 
* How `cs_files` look like after refreshing?
* What's in `~/.cs_cache` regarding this project?

To fix anything I need to be able to reproduce it. Your current directory structure seems pretty straightforward. I don't get why Vim-CtrlSpace does not map `src` correctly. 

If possible please record a quick show through asciinema.

Regarding workspace saving, nope you should be able to save workspace without any directory switching, from any directory inside a project. Unless you are in a subproject. Moreover, Vim-CtrlSpace doesn't require any manual changing of current working directory.

**Comment by kangic** [comment]
Thank you for response very soon.

First, I resolved a problem to swtich the path after open the file in 'src' directory.
I don't know exactly, but I think it was occured by my bookmark occured.(I did save a bookmark to 'src' directory before.)

Now, answer your questions.
* Could you write more about your environment?
  - Ubuntu 14.04 64bit
  - zsh, tmux
  - Using vundle plugin for managing vim plugins
* Could you verify the problem with a vanilla Vim and all other plugins turned off?
  - Sorry, I don't know vanilla Vim.
  - I turned off plugins and then tested it. But same as before.
* How cs_files look like after refreshing?
  - Nothing. I didn't find the change anything.
* What's in ~/.cs_cache regarding this project?
  - I did save the bookmark as below.
    - CS_BOOKMARK: /home/raymondk/works/github/eznetpp/src|CS_###_CS|eznetpp
  - I modified the bookmark when I recorded.

Here's my asciinema.
https://asciinema.org/a/7jafjn3i87umcjmld17avwgg1

**Comment by szw** [comment]
Well good to know it works for your now :). Indeed it might behave unpredictably if the bookmark has been saved to a deeper directory than assumed.

**Comment by kangic** [comment]
Oh. I'm sorry to do not write my result clearly.
I didn't resolve the problem.
You can see my problem remain still, if you watch my asciinema.
I can't load the correct source files. Almost files are blank files after load the workspace.

**Comment by szw** [comment]
Ok, did `:messages` returns something? I see there is CS_SESSION file in your project root directory. It should be deleted after successfully session loading. Could you try to `:source CS_SESSION` and see if any errors occur?

**Comment by kangic** [comment]
* `:messages`
  - The variable g:airline_enable_branch is deprecated and may not work in the future. It has been replace...
  - The variable g:airline_enable_syntastic is deprecated and may not work in the future. It has been repl...

`:source CS_SESSION` occurs `E484: Can't open file CS_SESSION`.

**Comment by szw** [comment]
Try `:source ./CS_SESSION`. It's clearly present on your asciinema (1:45).

**Comment by kangic** [comment]
I turn on vim in my project root path and run command `:source CS_SESSION`. Is it right?
```
The variable g:airline_enable_branch is deprecated and may not wo...
The variable g:airline_enable_syntastic is deprecated and may not...
"CMakeLists.txt" 21L, 501C
"CMakeLists.txt" 21L, 501C
"io_manager.cc" 123L, 3374C
"io_manager.cc" 123 lines --0%--
```

**Comment by szw** [comment]
Please post a gist with your .vimrc.

**Comment by kangic** [comment]
Here's my vimrc in my github repo.
https://github.com/kangic/dot_vimrc/blob/master/vimrc

**Comment by kangic** [comment]
Oh! Maybe I got the problem.

I loaded my workspace correctly after disabled below options.
```
"====== set auto changing to current dir ======
set autochdir
autocmd BufEnter * silent! lcd %:p:h
```

Thank you for your effort to my question.

**Comment by szw** [comment]
Yeah, session loading works poorly with autochdir. Actually Vim-CtrlSpace can turnoff autochdir temporarily, but of course it cannot detect custom autocmd commands.
