### ISSUE TITLE
ctrlspace generates improper `edit` command for file path with space in it.

### ISSUE THREAD

**Issue by Mudox** [szw/vim-ctrlspace#138]
I am using Neovim in iTerm2 on OS X 10.10.5

To reproduce it:

+ create a directory tree as follows:

    ![1](https://cloud.githubusercontent.com/assets/2283394/9433566/44e9b3da-4a67-11e5-8d21-8edbda8ecfff.png)

+ apply `git init` to 'testdir/dir_a'
+ open the 2 'test.txt' files in nvim splitted vertically

    ```sh
    nvim -O 'testdir/dir_a/test.txt' 'testdir/dir_b/dir with space/xxx/test.txt'
    ```
+ save workspace into __testdir/dir_a/.git/cs_workspace__, as instructed by ctrlspace doc

+ run `grep '^edit' 'testdir/dir_a/.git/cs_workspaces' | sort`, I got:

   > edit /private/tmp/testdir/dir_b/dir with space/xxx/test.txt
   > edit /private/tmp/testdir/dir_b/dir\ with\ space/xxx/test.txt
   > edit test.txt
   > edit test.txt

The first `edit` command made nvim emit the following complain when I loaded the workspace afterwards:

![3](https://cloud.githubusercontent.com/assets/2283394/9433950/ae6162a0-4a6b-11e5-8143-7f6b946c9183.png)

Here is the generated __cs_workspace__ file of above example:

> CS_LAST_WORKSPACE: test
> CS_WORKSPACE_BEGIN: test
> let SessionLoad = 1
> let s:so_save = &so | let s:siso_save = &siso | set so=0 siso=0
> let v:this_session=expand("<sfile>:p")
> silent only
> cd /private/tmp/testdir/dir_a
> if expand('%') == '' && !&modified && line('$') <= 1 && getline(1) == ''
>   let s:wipebuf = bufnr('%')
> endif
> set shortmess=aoO
> badd +1 test.txt
> argglobal
> silent! argdel *
> argadd test.txt
> edit test.txt
> edit /private/tmp/testdir/dir_b/dir with space/xxx/test.txt
> edit test.txt
> set splitbelow splitright
> wincmd _ | wincmd |
> vsplit
> 1wincmd h
> wincmd w
> set nosplitbelow
> set nosplitright
> wincmd t
> set winheight=1 winwidth=1
> exe 'vert 1resize ' . ((&columns * 136 + 136) / 272)
> exe 'vert 2resize ' . ((&columns * 135 + 136) / 272)
> argglobal
> let s:l = 1 - ((0 * winheight(0) + 29) / 58)
> if s:l < 1 | let s:l = 1 | endif
> exe s:l
> normal! zt
> 1
> normal! 0
> wincmd w
> argglobal
> edit /private/tmp/testdir/dir_b/dir\ with\ space/xxx/test.txt
> let s:l = 1 - ((0 * winheight(0) + 29) / 58)
> if s:l < 1 | let s:l = 1 | endif
> exe s:l
> normal! zt
> 1
> normal! 0
> wincmd w
> exe 'vert 1resize ' . ((&columns * 136 + 136) / 272)
> exe 'vert 2resize ' . ((&columns * 135 + 136) / 272)
> tabnext 1
> if exists('s:wipebuf') && getbufvar(s:wipebuf, '&buftype') isnot# 'terminal'
>   silent exe 'bwipe ' . s:wipebuf
> endif
> unlet! s:wipebuf
> set winheight=1 winwidth=20 shortmess=filnxtToOI
> let s:sx = expand("<sfile>:p:r")."x.vim"
> if file_readable(s:sx)
>   exe "source " . fnameescape(s:sx)
> endif
> let &so = s:so_save | let &siso = s:siso_save
> doautoall SessionLoadPost
> unlet SessionLoad
> " vim: set ft=vim :
> CS_WORKSPACE_END: test

**Comment by szw** [comment]
Thanks for spotting this one! :) Hopefully there are no more unescaped places :sunglasses: :smirk:

**Comment by Mudox** [comment]
:+1: for your quick response, it fixed.
