### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by sittim** [szw/vim-ctrlspace#139]
I fell in love with this plug-in, except one announce, I mapped ` nnoremap <silent><C-p> :CtrlSpace O<CR> `, but every time I narrow down to a file by fuzzy searching it, I have to hit <CR> twice, any way to make it open the file by hitting <CR> just once?

I hate looking for files in a list, so all of my file switching is done via <C-p> that is why the double <CR> is driving me crazy.  I do not use tab lists even buffer lists.

**Comment by szw** [comment]
Great :). Well how about <Tab> key? ;)

**Comment by sittim** [comment]
OK, stupid me, yes that works, I will have to retrain my fingers, awesome suggestion...

**Comment by szw** [comment]
:v: The _rule of thumb_ is that `<Tab>` is the more finishing action (a _choose and close_ kind) and `<Space>` is the opposite (_choose and hold/wait_). And `<CR>` lies somewhere between.
