### ISSUE TITLE
Fuzzy Open

### ISSUE THREAD

**Issue by sittim** [szw/vim-ctrlspace#140]
Hi,

Quick question for you,

- my project folder is `/work/c1202-f5335v2/`, in this folder, i have a file `coap/unittest/option_test.cpp`.
- If I run `:pwd` command in VIM, I get `/work/c1202-f5335v2`
- if I run `ag -l --nocolor -g ""` from project folder one of my entries is: `coap/unittest/option_test.cpp`
-Now when I run `<ctrl-space>` and `o`, fuzzy search is not able to find the `option_test.cpp`.  Why would it be, am I doing something wrong?  It seems like the files that were created after I created the project, have not been showing up while fuzzy searching.  Should I be running an update?

**Comment by sittim** [comment]
I did little more research and found that when do the `<o>` command, my file list is really outdated.  Should I be doing something to keep the list update?

**Comment by szw** [comment]
I bet you didn't refresh your file list (`<r>`) :)

**Comment by sittim** [comment]
Thank you, I added a pull request with some text to readme file for idiots like me who cannot read help files.  I actually did scan through commands and missed the `<r>`.

**Comment by szw** [comment]
Don't worry! It's hard to find out everything for the first time. I believe it's worth to document things better. Perhaps on a dedicated project page or wiki. With some use cases and user scenarios to make a lot of ideas more clear.
