### ISSUE TITLE
Swap file recovery integration?

### ISSUE THREAD

**Issue by dodomorandi** [szw/vim-ctrlspace#143]
Have you ever used CtrlSpace on a remote SSH session? It is awesome as always. However, sometimes the SSH session hangs, and when you re-open your workspace, you have to recover every file.
I was just wandering if it is possible to use the current implementation of CtrlSpace to handle the recovery process for the files of the workspace. If not, is it possible to implement some sort of management system?

Great work, as always!

**Comment by szw** [comment]
I personally remove swap files entirely in my vim config. But regarding remote work in a console Vim through SSH, have you tried tmux? It can hold your session and allows you to disconnect and reattach later.

**Comment by dodomorandi** [comment]
Hey, nice one! I never tried tmux... and that is exactly what I wanted! In this way, no more problems about disconnections and swap files!

Thank you so much!
