### ISSUE TITLE
+/- keys for moving selected tab doesn't works 

### ISSUE THREAD

**Issue by unclechu** [szw/vim-ctrlspace#146]
When I go to CtrlSpace tab list and try to move tabs by '+' or '-' keys — nothing happens except one thing, selected tab becomes active.

P.S. [My config](https://github.com/unclechu/vimrc2).

**Comment by szw** [comment]
I suspect `{` and `}` also don't work, right? What Vim version and what OS do you have? Have you tried with vanilla Vim? (If not please try to comment out all other plugins besides Vundle and CtrlSpace). Did `:messages` show any errors?

**Comment by unclechu** [comment]
@szw `{` `}` also doesn't works. I tested it on `gvim` and console `vim`.
Version of vim is 7.4.475
OS: Fedora 21
`uname -a`: Linux usoftchu 4.1.6-100.fc21.x86_64 #1 SMP Mon Aug 17 22:20:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
`:meesages`  doesn't show any errors.
I remember recently it worked.

**Comment by szw** [comment]
How about disabling all other plugins?

**Comment by unclechu** [comment]
@szw I disabled all other plugins, all my own hotkeys and other my configs but it doesn't helps.

**Comment by szw** [comment]
Indeed I can confirm presence of this bug. Thanks for reporting!

**Comment by szw** [comment]
It seems the number of places (_N_) in `tabm` command is obligatory in that version/os. Now it should work. Thanks again for reporting!

**Comment by unclechu** [comment]
@szw Now it works, thanks for good work!
