### ISSUE TITLE
Search mode

### ISSUE THREAD

**Issue by melta** [szw/vim-ctrlspace#147]
Hi,

Is it possible to use the following characters in search mode: "_", "-", "."? When I tried to use them I got the following message: "Key ... doesn't work in this view."  Sometimes there are files like the following:
1 "filename.txt"
2 "file_name.txt"
or
1. "filename.txt"
2. "file-name.txt"
and it is impossible to specify search string to match exactly the file with underscore or dash in name. If there are only 2 or 3 such files it is not problem at all, but if there are lot of such files it became hard to match exactly the one you need.

Another thing that I noticed is that when I start typing search string in search mode some of letters is missed. It always happened when I quickly type file name that I want to find. 

Thank you for your awesome plugin.

**Comment by melta** [comment]
Just noticed that the issue with "missed" letters in search string only arise when I search through a lot of files (more then 20000).  Looks like fuzzy finder freezes during search in projects with a lot of files and that is why it looks like I didn't type some letters. ;)

**Comment by ryrych** [comment]
By default search timing is 100ms as most users don't have projects consisting of that amount of files. I'd recommend you increase the timing to 200-300ms. You can find how to do it [here](https://github.com/szw/vim-ctrlspace/blob/master/doc/ctrlspace.txt#L309-L320) or [here](https://github.com/szw/vim-ctrlspace/blob/master/doc/ctrlspace.txt#L1113-L1126).

Fuzzy search in `vim-ctrlspace` doesn't support characters you mentioned.

**Comment by melta** [comment]
Thank you very much for the advice, it did the trick. Now I am even more happier than I was :)

**Comment by szw** [comment]
:+1:
