### ISSUE TITLE
wrap <C-^> to avoid cluttering tab buffer list

### ISSUE THREAD

**Issue by Konfekt** [szw/vim-ctrlspace#149]
To avoid accidentally cluttering the current tab buffer list: Could `<c-^>`  display the previous buffer in the current tab only if it is either listed in the current tab or not listed in another tab? Otherwise, switch to the most recently accessed tab that lists it?

By cluttering is meant, that when switching tabs, `<c-^>` won't carry to the tab where the buffer was last displayed but add it to the current tab.

**Comment by szw** [comment]
Hmm... you can always alter the default `<C-^>` on your own and I'm not sure if the plugin should change that default behavior. The simplest thing could be just use own mappings for `<C-6>` and `<C-^>` to call for example `:CtrlSpace P` command instead:

```VimL
nnoremap <silent><C-6> :CtrlSpace P<CR>
nnoremap <silent><C-^> :CtrlSpace P<CR>
```

It should prevent cluttering by limiting `<C-^>` to the scope of current tab only (leveraging CtrlSpace history tracking).

**Comment by Konfekt** [comment]
My bad, that's it. Didn't know it's already there. Doesn't switch tabs but it's questionable if it ought to after all. Added the above line to `vimrc`.

**Comment by Konfekt** [comment]
By the way, where is `CtrlSpace P` documented? Could not find it in the doc file.

**Comment by szw** [comment]
In Vim-CtrlSpace itself - try `<C-Space>?` or `<C-Space>?<CR>`:
![zrzut ekranu 2015-10-25 o 19 13 33](https://cloud.githubusercontent.com/assets/341899/10717165/f404896c-7b4f-11e5-90fd-7e6ec703bb61.png)

**Comment by Konfekt** [comment]
Thanks, it used to be in the readme and doc, that's probably what made me wonder.
