### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by stephencheng** [szw/vim-ctrlspace#155]
I noticed quite major performance issue

For a project workspace with 8000 files:

FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   21  50.465620   0.031307  ctrlspace#window#Toggle()
   21  47.892432   0.110899  ctrlspace#engine#Content()
   24  45.550240   0.000315  ctrlspace#search#UpdateSearchResults()
    1  45.073776   0.272803  <SNR>225_computeLowestNoises()
 7200  44.800973   7.437476  <SNR>225_findLowestSearchNoise()
275622  37.363497             <SNR>225_findSubsequence()
  186   8.754593   0.018403  ctrlspace#keys#Keypressed()
   47   3.601945   3.584594  <SNR>210_OnBufferVisit()
   41   3.511796   0.019410  ctrlspace#window#Kill()
    8   3.471697   0.000495  <SNR>96_toggleListView()
   26   2.517294             UltiSnips_FileTypeChanged()
   21   2.502536   0.130958  <SNR>221_setUpBuffer()
    4   2.437956   0.000516  ctrlspace#keys#common#ToggleFileMode()
    1   2.021942   1.977125  commandt#CommandTShowFileFinder()
    1   1.523261   0.000034  ctrlspace#keys#file#Refresh()
    1   1.523227   0.003620  ctrlspace#files#RefreshFiles()
   20   1.455624   1.455572  <SNR>225_prepareContent()
    8   1.322701   0.000294  nerdtree#invokeKeyMap()
    8   1.322407   0.000720  247()
    3   1.292691   0.000266  ctrlspace#keys#buffer#SwitchTab()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
275622             37.363497  <SNR>225_findSubsequence()
 7200  44.800973   7.437476  <SNR>225_findLowestSearchNoise()
   47   3.601945   3.584594  <SNR>210_OnBufferVisit()
   26              2.517294  UltiSnips_FileTypeChanged()
    1   2.021942   1.977125  commandt#CommandTShowFileFinder()
   20   1.455624   1.455572  <SNR>225_prepareContent()
   13              1.242612  CommandTListMatches()
    7   1.030913   0.605553  ctrlspace#files#CollectFiles()
  331   0.689450   0.380945  302()
  252              0.366928  <SNR>207_MarksList()
 4368              0.347654  <SNR>207_ToggleSign()
 6728              0.299307  <SNR>196_get_syn()
    1  45.073776   0.272803  <SNR>225_computeLowestNoises()
 3589              0.230682  airline#highlighter#exec()
   33   0.641130   0.174303  airline#highlighter#highlight()
 3364   0.532585   0.169444  airline#highlighter#get_highlight()
27392              0.159307  ctrlspace#engine#CompareByText()
   21   2.502536   0.130958  <SNR>221_setUpBuffer()
  411              0.129728  UltiSnips_CursorMoved()
   21  47.892432   0.110899  ctrlspace#engine#Content()

Another case, with 450 files:

FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   18   6.763343   0.014560  ctrlspace#window#Toggle()
   47   4.872431   0.004809  ctrlspace#keys#Keypressed()
   18   4.692355   0.062027  ctrlspace#engine#Content()
   25   3.274447   0.000403  ctrlspace#search#UpdateSearchResults()
   18   2.671048   2.670995  <SNR>219_prepareContent()
   18   2.034285   0.110239  <SNR>215_setUpBuffer()
   21   1.937496             UltiSnips_FileTypeChanged()
    2   1.803196   0.000048  ctrlspace#keys#file#Refresh()
    2   1.803148   0.000582  ctrlspace#files#RefreshFiles()
    4   1.802830   0.000225  <SNR>96_toggleListView()
    3   1.669129   0.000089  ctrlspace#keys#common#ToggleFileMode()
    6   1.561664   0.045092  <SNR>219_computeLowestNoises()
 1338   1.516572   0.396524  <SNR>219_findLowestSearchNoise()
13575   1.120048             <SNR>219_findSubsequence()
    3   0.915465   0.000200  ctrlspace#search#SwitchSearchMode()
    1   0.525812   0.000017  ctrlspace#keys#search#SwitchOff()
    1   0.422517   0.000028  ctrlspace#keys#file#LoadFile()
    1   0.422489   0.000218  ctrlspace#files#LoadFile()
    1   0.397177   0.001440  <SNR>217_loadFileOrBuffer()
    2   0.389699   0.000029  ctrlspace#keys#common#EnterSearchMode()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
   18   2.671048   2.670995  <SNR>219_prepareContent()
   21              1.937496  UltiSnips_FileTypeChanged()
13575              1.120048  <SNR>219_findSubsequence()
 1338   1.516572   0.396524  <SNR>219_findLowestSearchNoise()
   16   0.184977   0.183842  <SNR>210_OnBufferVisit()
  120              0.181719  <SNR>207_MarksList()
 2080              0.163832  <SNR>207_ToggleSign()
19190              0.139337  ctrlspace#engine#CompareByText()
   18   2.034285   0.110239  <SNR>215_setUpBuffer()
    8   0.188302   0.099798  ctrlspace#files#CollectFiles()
 2440              0.095706  <SNR>196_get_syn()
   21   0.081527   0.081304  <SNR>20_LoadFTPlugin()
 3998              0.064021  ctrlspace#engine#CompareByNoiseAndText()
   18   4.692355   0.062027  ctrlspace#engine#Content()
 1220   0.170510   0.052714  airline#highlighter#get_highlight()
  948              0.051905  airline#highlighter#exec()
    6   1.561664   0.045092  <SNR>219_computeLowestNoises()
   21   0.046580   0.044346  <SNR>7_SynSet()
   10   0.118525   0.031111  airline#highlighter#highlight()
   61   0.248771   0.030823  371()

I found my vim start quit lagging and not responsive when using ctrlspace hence tracing down to this. Not sure what you can do, but see if it helps.

**Comment by szw** [comment]
What file engine is reported when you open Vim-CtrlSpace window and press `?` (the first line)? For example in my case it is:
```
⌗ CtrlSpace 5.0.6 (engine: file_engine_darwin_amd64)
```

**Comment by stephencheng** [comment]
Sorry, it's my bad, I mistakenly excluded the bin directory causing the issue.
