### ISSUE TITLE
how to remap [ and ] as , . to switch tab

### ISSUE THREAD

**Issue by stephencheng** [szw/vim-ctrlspace#157]
I'd like to remap the key, but not able to follow the doco to make it.

The function traced to is:
	call ctrlspace#keys#AddMapping("ctrlspace#keys#tab#SwitchTab", "Tab", ["[", "]"])

how to fill in the data structure there below?

let g:CtrlSpaceKeys = { "Tab": { ",": "func-switch-left", ".": "func-switch-right" } }

Thanks

**Comment by szw** [comment]
Here's a working example:

```VimL
function! SwitchTabWrapper(k)
	if a:k == ","
		call ctrlspace#keys#tab#SwitchTab("[")
	elseif a:k == "."
		call ctrlspace#keys#tab#SwitchTab("]")
	endif
endfunction

let g:CtrlSpaceKeys = { "Tab": {
			\ ",": "SwitchTabWrapper",
			\ ".": "SwitchTabWrapper"
			\} }
```

Additionally you can remove the existing `[` and `]` mappings with:

```VimL
let g:CtrlSpaceKeys["Tab"]["]"] = "ctrlspace#keys#Undefined"
let g:CtrlSpaceKeys["Tab"]["["] = "ctrlspace#keys#Undefined"
```

**Comment by stephencheng** [comment]
Thanks, great, now this is really handy.
