### ISSUE TITLE
Where are all the config files?

### ISSUE THREAD

**Issue by tomparys** [szw/vim-ctrlspace#161]
Hi, something went cock's up with my install and I'm losing a tab page here and there. I'd like to purge all config/setting files to start anew with a clean slate. Could you give me pointers to where I can find all of them (on Linux specifically)?

I deleted all the `cs_workspaces` and `cs_files` I could find as well as the `~/.cs_cache`, but I think I'm still missing some.

Big thanks for a great plugin!

**Comment by szw** [comment]
Hi! I think that's pretty all. I cannot recall anything more. Of course `cs_workspaces` and `cs_files` are supposed to be created in each project directory you used within the plugin.

**Comment by tomparys** [comment]
Thanks! So I found out my issue is not related to broken settings, but most likely to my use of neovim. Do you use neovim? Have you done any testing on it?

**Comment by tomparys** [comment]
Thanks! I found out my issue is not due to settings, but due to a bug, I'll make a new issue.
