### ISSUE TITLE
nomodifiable files are not getting listed

### ISSUE THREAD

**Issue by justrajdeep** [szw/vim-ctrlspace#41]
Hi,

I have started using the plugin since last week and it is amazing. it requires some workflow changes but i guess it is worth the effort.

One thing that i am observing is that if the has a 'nomodifiable' flag it does not get listed in the buffer list.

Is is something in the setting that i might be missing.

**Comment by szw** [comment]
Hi @justrajdeep! Your use case is rather rare, but I cannot really find any good reason why `nomodifiable` buffers cannot be listed. I don't recall any edge case related to it right now... I suspect it's something I borrow [from here](https://github.com/roblillack/vim-bufferlist/blob/master/plugin/bufferlist.vim#L62). 

Anyway, technical buffers should not be listed (buflisted) and that's something we check anyway. So I guess nothing really wrong would happen if we allow to navigate to `nomodifiable` buffers.

**Comment by justrajdeep** [comment]
Thanks szw for following it up. Really appreciate it.

**Comment by szw** [comment]
Feel free to test the PR branch. I'm testing it too and everything seems fine so far, so I'm about to merge it. But perhaps you could verify if it solves your case as well..?

**Comment by szw** [comment]
Merged :). Let me know if anything unexpected occurs :)
