### ISSUE TITLE
Have it save the unsaved file?

### ISSUE THREAD

**Issue by sinkingshriek** [szw/vim-ctrlspace#70]
Hi, I love this plugin so far and while I like the idea of saving the workspace on exit and automatically loading it back, I was wondering if it can save the unsaved files as well. There are times when I just force quit vim and in that scenario it would be nice for this plugin to save the my not yet saved files as well you know, just like what Sublime Text does. 

Very powerful plugin btw. :heart: it.

**Comment by szw** [comment]
Hmm, actually I'm not sure about putting this feature straight to the plugin, but here's a working solution leveraging new CtrlSpace `Buffers()` function. Hopefully it will help you :)

```VimL
function! SaveAll()
    for b in map(keys(ctrlspace#buffers#Buffers(0)), "str2nr(v:val)")
        if getbufvar(b, '&modified')
            let bufname = bufname(b)

            if !strlen(bufname)
                let bufname = "NONAME_" . b . "_" . localtime()
                let ext     = getbufvar(b, "&ft")

                if !empty(ext)
                    let bufname .= "." . ext
                endif
            endif

            silent exe ":b " . b
            silent exe ":w " . fnameescape(bufname)
        endif
    endfor
endfunction

autocmd VimLeavePre * call SaveAll()

let g:CtrlSpaceSaveWorkspaceOnExit = 1
```

Cheers!

s.
