### ISSUE TITLE
Dotfiles are not listed

### ISSUE THREAD

**Issue by DXist** [szw/vim-ctrlspace#82]
It would be nice to list dotfiles when search pattern starts with dot.

**Comment by szw** [comment]
For `ag` you can use 

```
let g:CtrlSpaceGlobCommand = 'ag -lu --nocolor -g ""'
```

to get hidden files displayed. Then however it does not obey `.gitignore` anymore. But it still should follow `g:CtrlSpaceIgnoredFiles`.

**Comment by DXist** [comment]
Thank you for the tip! Actually `ag` has `--hidden` option which I've added to `ag` alias.

**Comment by szw** [comment]
Indeed, it's actually even better. I think it's a good solution for now and will add this tip to the docs.

**Comment by DXist** [comment]
Yes, it's a good idea. By the way I've just upgraded to`vim-ctrlspace 5` - thank you for great work!

**Comment by szw** [comment]
Thanks! :)
