### ISSUE TITLE
bufdo saves all buffers in current tab

### ISSUE THREAD

**Issue by napseis** [szw/vim-ctrlspace#94]
hi,

Let's say I have 3 tabs with a few buffers inside.
I want to run bufdo %s/behavior/behaviour/g
What happens is all my buffers get inserted in the active tab, while i would like to stay them where they are.
Is there a workaround ?

Thanks

**Comment by szw** [comment]
Yes, you're right. The way to overcome this might be to add a new tab (`l`, `a`) and perform the `:bufdo` command there. It collect all buffers in that new tab, but the other remain unchanged. Then after the command is completed you can just close that tab with `l`, `c`. Let me know how do you find it :)
