### ISSUE TITLE
add 'Vim tabs madness' article to documentation

### ISSUE THREAD

**Issue by ryrych** [szw/vim-ctrlspace#96]
As I didn't find 'Buffers, Windows, and Tabs' section helpful (have started using vim a few weeks ago), I was looking for more down-to-earth explanation of buffers/windows/tabs concepts and this article turned out to be very helpful:

https://joshldavis.com/2014/04/05/vim-tab-madness-buffers-vs-tabs/

**Comment by szw** [comment]
:+1:

**Comment by jdavis** [comment]
:+1:
