### ISSUE TITLE
add screenshots of workspace(s) from a real project

### ISSUE THREAD

**Issue by ryrych** [szw/vim-ctrlspace#97]
I'm sure that the illustration displaying the relationships is very good when you're already familar with the plugin, but from my perspective (vim newbie, using RubyMine) is not enough. Some screenshots / images would add more value.

**Comment by szw** [comment]
I'm not. I don't like it actually ;). Yeah, you're right documentation needs a lot of screenshots and simpler explanations. Also I think the key reference should be gathered together in one section.
