### ISSUE TITLE
Search help mode

### ISSUE THREAD

**Issue by rgrinberg** [szw/vim-ctrlspace#98]
E.g. After `:CtrlSpace` and hitting `?` I'd like to search help with `/` or something. Currently that doesn't work.

**Comment by szw** [comment]
Hmm... interesting idea! I'll check that later to see how much work it could take.

**Comment by yacoob** [comment]
Even better, instead of searching just filter out the lines that don't contain the query string. Just like ctrlspace's Search Mode. :)

**Comment by szw** [comment]
Yeah, I like this approach. But the Help view is considered to be available always, in any mode. It's legit to see help even when typing in the Search Mode input. The question therefore is, how to search/filter help text for Search Mode? Display a second input box or...? I'm open to any ideas regarding user interface and usability.

**Comment by yacoob** [comment]
I must be missing something - if you toggle help while in search mode, all subsequent input seems not to be going to the search field anyway. Or at least, that's how it behaves here.

**Comment by szw** [comment]
That's true. My point was about the UI. Imagine you are pressing `<?>` while in Search Mode. The help for Search Mode is shown. What should happen next if you press `</>`? Another Search Input should occur in the status bar?

**Comment by yacoob** [comment]
Ah - yes, probably. At the top of the buffer perhaps?

**Comment by szw** [comment]
I don't know.. but it definitely needs a separate UI for searching. Anyway, it's clear for me that this feature should be there so it goes to the top of my TODO ;).

**Comment by szw** [comment]
Now it's possible to search keys in a seperate buffer. Press `<CR>` in the Help View :)
